version: "3"
services:
  mysql:
    build:
      context: ./docker/mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
          - type: bind
            source: ./mysql
            target: /var/lib/mysql
    ports:
      - 3306:3306
  php_apache:
    build:
      context: ./docker/php
      args:
        php_version: ${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-php_apache
    volumes:
        - type: bind
          source: ./www
          target: /var/www/html
    depends_on:
        - mysql
    ports:
      - ${PHP_PORT}:80
    links:
      - mysql
  phpmyadmin:
    image: ${PHPMYADMIN_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}